/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.modmappings.app;

import org.modmappings.list.LinkedList;

import static org.modmappings.utilities.StringUtils.join;
import static org.modmappings.utilities.StringUtils.split;
import static org.modmappings.app.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        System.out.println(join(tokens));
    }
}
